type: "requirements"

users:
 - &Authority GunClear Platform Manager
 - &User Registered GunClear User
 - &Gunero Gunero Plasma Sidechain
 - &Operators Gunero Plasma Sidechain Operators
 
assets:
 - &GunToken token representing a known firearm
 
contracts:
 - &TokenManager GunClear Token contract
 - &Authlist User Authlist contract
 - &PlasmaBridge Gunero Bridge contract

times:
 - &DisputePeriod 30 day dispute period
 - &PlasmaCycle 7 day Gunero synchronization cycle

requirements:
 # Token contract requirements
 - The *TokenManager shall allow the *Authority to mint a new *GunToken.
 - The *TokenManager shall allow a *User to transfer their *GunToken to any other *User.
 - The *TokenManager shall verify the correct handling of the *GunToken if transferred to a smart contract address.
 - The *TokenManager shall allow a *User to transfer their *GunToken into the *PlasmaBridge iff they provide the nullifier.
 - The *TokenManager shall allow any *User to burn any *GunToken they own.
 # Authlist contract requirements
 - The *Authlist shall allow the *Authority to change a *User's current status to authorized at any time.
 - The *Authlist shall allow the *Authority to change a *User's current status to in review at any time.
 - The *Authlist shall allow the affected *User to dispute a review status within the *DisputePeriod.
 - The *Authlist shall allow the *Authority to finalize a change in status after the *DisputePeriod.
 - The *Authlist shall maintain the current merkle root of the associated list for every status update.
 - The *Authlist shall emit an event that allows a *User to keep track of updates to their merkle branch.
 # Plasma contract requirements
 - The *PlasmaBridge shall allow a deposit of any *GunToken that includes a valid nullifier with the deposit.
 - The *PlasmaBridge shall emit an event including the nullifier for any *GunToken it has received.
 - The *PlasmaBridge shall allow a *User to withdraw a *GunToken from *Gunero that they control at any time.
 - The *PlasmaBridge shall allow the *Operators to publish the *Gunero state root hash at most once during a *PlasmaCycle.
 - The *PlasmaBridge shall allow the *Operators to publish the *Authlist root hash at most once during a *PlasmaCycle.
